### ISSUE TITLE
[개선사항] 메자이 이미지 개선

### ISSUE THREAD

**Issue by kimchijinju** [mejaiGG/Frontend#7]
1. 1번 개선안

    잔디 색깔처럼 차별화를 주는게 좋을 것 같습니다 (판수가 적은 날은 이미지 흐리게, 많은 날은 이미지 선명하게)
2. 메자이와 숫자가 박힌 이미지를 25개 만들어서 판수 표시하면 좋을듯? (고화질 이미지가 없어서 아마 폰트로 넣어야 하긴할듯합니다.)
    1번 아이디어랑 합쳐서 판수 적은날은 이미지 흐리게 같이 해도 좋을듯 함
![스크린샷 2024-04-07 오후 8 28 12](https://github.com/mejaiGG/Frontend/assets/92737157/586725ef-62b1-4913-bdff-5d5797140ef6)
![스크린샷 2024-04-07 오후 8 29 45](https://github.com/mejaiGG/Frontend/assets/92737157/22c3ce56-78d7-440e-876d-90323e5d635f)
![스크린샷 2024-04-07 오후 8 30 17](https://github.com/mejaiGG/Frontend/assets/92737157/17e58b2d-e7f9-404e-8b36-6d326cd53e3f)

**Comment by donghyun1998** [comment]
1번아이디어 좋은 것 같습니다. 기존에 css로 숫자 넣는건 너무 눈아프고 짜쳤어요
2번아이디어는 더 좋은 것 같습니다. 이건 다같이 논의해보죠? 전 너무 좋아요

**Comment by donghyun1998** [comment]
해결
