### ISSUE TITLE
[개선사항] 이거 해당 년도도 보여주면 좋을 것 같아요!!

### ISSUE THREAD

**Issue by Hawardshin** [mejaiGG/Frontend#8]
![스크린샷 2024-04-07 오후 8 20 48](https://github.com/mejaiGG/Frontend/assets/92737157/b4d0c593-8139-4265-b2a9-bb6e073d329b)

**Comment by donghyun1998** [comment]
아 이건 금방 추가 가능합니다. 빌드 오류 풀리퀘 머지되면 바로 작업해서 올릴게요~

**Comment by donghyun1998** [comment]
우리 근데 2023년도도 지원하게 하나요? 그러면 year 처리하는 부분 추가해야합니다

**Comment by Hawardshin** [comment]
음 일단은 1차배포에서는 전 6개월 정도로 제한을 두고 가져오게 하고 대신 년도는 표시해주면 좋을듯합니당..!

**Comment by donghyun1998** [comment]
전 6개월 확인입니당
